stackName: eSCDemoNext12Stack
org: eSC2112
app: eSCServerlessNextjs12
escNextApp:
  component: "@sls-next/serverless-component@3.4.0"
  inputs:
    useServerlessTraceTarget: true
    cloudfront:
      comment: ${stackName}
    
