import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Image Resizing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Image
            src="https://esc-alpha.vercel.app/assets/rider_female.png"
            alt="Female Rider"
            width={100}
            height={92}
          />

          <h2>Medium &rarr;</h2>
          <Image
            src="https://esc-alpha.vercel.app/assets/rider_female.png"
            alt="Female Rider"
            width={200}
            height={184}
          />

          <h2>Original &rarr;</h2>
          <Image
            src="https://esc-alpha.vercel.app/assets/rider_female.png"
            alt="Female Rider"
            width={300}
            height={276}
            // blurDataURL="data:..." automatically provided
            //placeholder="blur" // Optional blur-up while loading
          />

          <Image
            src="https://esc-alpha.vercel.app/assets/rider_male.png"
            alt="Male Rider"
            width={100}
            height={92}
            // blurDataURL="data:..." automatically provided
            //placeholder="blur" // Optional blur-up while loading
          />

          <h2>Medium &rarr;</h2>
          <Image
            src="https://esc-alpha.vercel.app/assets/rider_male.png"
            alt="Male Rider"
            width={200}
            height={184}
            // blurDataURL="data:..." automatically provided
            //placeholder="blur" // Optional blur-up while loading
          />

          <h2>Original &rarr;</h2>
          <Image
            src="https://esc-alpha.vercel.app/assets/rider_male.png"
            alt="Male Rider"
            width={300}
            height={276}
            //width={509}
            //height={468}
            // blurDataURL="data:..." automatically provided
            //placeholder="blur" // Optional blur-up while loading
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
